# Generated by Django 3.2.11 on 2022-01-30 09:50

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('batch_photo', models.ImageField(blank=True, null=True, upload_to='batches/')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(max_length=128)),
                ('bio', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('home_town', models.CharField(blank=True, choices=[('Kathmandu', 'Kathmandu'), ('Taplejung', 'Taplejung'), ('Panchthar', 'Panchthar'), ('Illam', 'Illam'), ('Jhapa', 'Jhapa'), ('Terathum', 'Terathum'), ('Dhankuta', 'Dhankuta'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Okhaldhunga', 'Okhaldunga'), ('Udayapur', 'Udayapur'), ('Saptari', 'Saptari'), ('Siraha', 'Siraha'), ('Sindhuli', 'Sindhuli'), ('Dhanusa', 'Dhanusa'), ('Mohottari', 'Mohottari'), ('Sarlahi', 'Sarlahi'), ('Rautahat', 'Rautahat'), ('Bara', 'Bara'), ('Parsa', 'Parsa'), ('Makwanpur', 'Makwanpur'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Kavre', 'Kavre'), ('Sindhupalchok', 'Sindhupalchok'), ('Dolakha', 'Dolakha'), ('Dhanding', 'Dhanding'), ('Chitwan', 'Chitwan'), ('Lalitpur', 'Lalitpur'), ('Ramechhap', 'Ramechhap'), ('Myagdi', 'Myagdi'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahun', 'Tanahun'), ('Kaski', 'Kaski'), ('Parbat', 'Parbat'), ('Baglung', 'Baglung'), ('Syangja', 'Syangja'), ('Palpa', 'Palpa'), ('Gulmi', 'Gulmi'), ('Rupandehi', 'Rupandehi'), ('Nawalparasi', 'Nawalparasi'), ('Kapilbastu', 'Kapilbastu'), ('Argakhachi', 'Argakhachi'), ('Dang', 'Dang'), ('Salyan', 'Salyan'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Surkhet', 'Surkhet'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Kailali', 'Kailali'), ('Dadeldhura', 'Dadeldhura'), ('Doti', 'Doti'), ('Baitadi', 'Baitadi'), ('Kanchanpur', 'Kanchanpur'), ('Bhaktapur', 'Bhaktapur'), ('Dailekh', 'Dailekh'), ('Achham', 'Achham'), ('Rukum', 'Rukum'), ('Kalikot', 'Kalikot'), ('Jumla', 'Jumla'), ('Darchula', 'Darchula')], max_length=256, null=True)),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latest_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latest_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user/profile/')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ManyToManyField(blank=True, to='authentication.Batches')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
