# Generated by Django 3.2.11 on 2022-01-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220127_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
    ]
