# Generated by Django 3.2.11 on 2022-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('batch_photo', models.ImageField(blank=True, null=True, upload_to='batches/')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='homewtown',
            new_name='home_town',
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ManyToManyField(blank=True, to='authentication.Batches'),
        ),
    ]
