# Generated by Django 3.2.11 on 2022-01-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220127_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
