# Generated by Django 3.2.11 on 2022-01-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220128_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='Age',
        ),
    ]
