# Generated by Django 3.2.11 on 2022-01-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220122_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batches',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
