# Generated by Django 3.2.11 on 2022-01-22 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tripping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitedplaces',
            options={'verbose_name': 'Visited Place', 'verbose_name_plural': 'Visited Places'},
        ),
        migrations.AlterField(
            model_name='visitedplaces',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
