# Generated by Django 3.2.11 on 2022-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripping', '0002_auto_20220122_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitedplaces',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
