# Generated by Django 3.2.11 on 2022-01-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripping', '0003_auto_20220122_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_sponsor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='visitedplaces',
            name='location_score',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='visitedplaces',
            name='public',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitedplaces',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitedplaces',
            name='vendor',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tripping.vendor'),
        ),
    ]
