# Generated by Django 3.2.11 on 2022-01-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripping', '0005_alter_visitedplaces_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
