# Generated by Django 3.2.11 on 2022-01-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripping', '0007_alter_vendor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedplaces',
            name='location_score',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
